### ISSUE TITLE
String variable constants are not highlighted

### ISSUE THREAD

**Issue by wmysterio** [sannybuilder/dev#140]
```text
{$CLEO .cs}
0000:

const

handle = 10@

my_strs1 = 20@s   
my_strs2 = s$str

my_strv1 = 6@v
my_strv2 = v$str

end

0A93: terminate_this_custom_script
```

![](https://i.ibb.co/jH3Z0mX/image.png)

**Comment by wmysterio** [comment]
@x87 This is a report from Vital. As far as I understood, blue is expected. Color for variables, as in `handle = 10@` case.

**Comment by VitalRus95** [comment]
Sorry for having @wmysterio send this report instead of me, I was rather busy and only got rid of some routine now.
I may add that not only string constants, but also expressions constants are not highlighted, both in semantic and non-semantic modes. As for the colour, I expect it to follow the highlighting mode: if it's the semantic one, then strings should be the string colour if it's possible.

How the issue looks in my case:
![изображение](https://user-images.githubusercontent.com/73489604/117721912-1dc6db80-b1e9-11eb-9f3f-8db51b924882.png)

**Comment by x87** [comment]
@VitalRus95 try with this version (unzip to SB\lib)
[core.zip](https://github.com/sannybuilder/dev/files/6455105/core.zip)

sanny should highlight them as variables (blue).

>expressions constants are not highlighted

they probably should not. what color do you expect?

**Comment by x87** [comment]
>expressions constants, they are still not highlighted at all and not present in the pop-up list.

to be fair, I think this is a quirk in the language and should be avoided. By no means `actor.Angle(pld)` is a *constant*.

**Comment by wmysterio** [comment]
> By no means actor.Angle(plr) is a constant.

This entry looks more like some kind of macro than a constant in the usual sense.
