### ISSUE TITLE
Preserving user modifications during updates

### ISSUE THREAD

**Issue by x87** [sannybuilder/dev#148]
By the way, I noticed that templates are reset to standard ones after installing new versions, which is also an inconvenience, since I, for one, have my own CLEO template and slightly modified standard templates of conditions and loops. It would be cool to have them saved until a serious change is needed.

_Originally posted by @VitalRus95 in https://github.com/sannybuilder/dev/issues/130#issuecomment-857725748_

**Comment by x87** [comment]
One related feature to this is #74 It should extract custom opcodes from one single file to separate folders where they could follow different update flow.

**Comment by x87** [comment]
User templates: #154

**Comment by VitalRus95** [comment]
Thanks for the update! I've tried to add a custom template, and `templates.custom.txt` was successfully created!

Yet what I would also like to have is a possibility to hide default templates if there are custom ones with the same name. For instance, I've changed `ifthen` and `ifelse` by adding more indentation (4 spaces instead of 2 and an indentation after `then`/`else` to save even more time), and after that I had duplicates in templates menu.

The CLEO template story is the same as I told before: if one wants their own shared template, they'll have to manually edit all exclusive templates by either modifying or deleting them, yet these would be restored after a new version comes out, leading to new confusion and duplicates.

So, in order to keep my own CLEO template, I had to name it other way and save as a custom template, which means I can't use “New CLEO script” but have to create an empty file and insert my template. All in all, the largest inconvenience for me is that you cannot just change/overwrite the default templates, since they always get restored.

However, saving custom ones is a great step forward and a nice way to preserve and share template ideas, so I am grateful for this new feature! 👍 

P. S. A stupid thought has crossed my mind that templates could be shared just like new themes, he-he.

**Comment by x87** [comment]
>A stupid thought has crossed my mind that templates could be shared just like new themes, he-he.

If you have some useful templates to share, submit a pull request in https://github.com/sannybuilder/data

I will look into templates visibility.

**Comment by x87** [comment]
> what I would also like to have is a possibility to hide default templates if there are custom ones with the same name.

@VitalRus95 this has been implemented in v3.8.0-beta.0, please give it a try

**Comment by x87** [comment]
closing this discussion as templates have been implemented and opcodes are tracked in a separate ticket
