### ISSUE TITLE
Some enums won't work

### ISSUE THREAD

**Issue by VitalRus95** [sannybuilder/dev#168]
I have an issue with the enums for classes from SB Opcode Library. I use an opcode `Sound.AddOneOffSound(.0, .0, .0, 13)`, which is supposed to support an enum called `ScriptSound`, present in `enums.txt`. The function itself is described in `classes.db` the following way: `AddOneOffSound,018C,0,0,("x%f" "y%f" "z%f" "soundId: ScriptSound")`. But in SB, pressing Ctrl+Space doesn't show `ScriptSound` prompt, only the constants I use in the script.

**Comment by XMDS** [comment]
@VitalRus95  In fact, I don’t quite understand your description. Is there a screenshot example?  The range of the ScriptSound enumeration of the SA Sound command: 1000-1190.  They do not start from 0

**Comment by VitalRus95** [comment]
@XMDS, I forgot to mention it's for VC, not for SA. Seemann knows about this issue from Discord, he just asked me to remind him about it here. The problem is that this pop-up menu called be pressing Ctrl+Space doesn't show the necessary enum (I tried opening this prompt window for every parameter in the opcode, thinking that maybe their order was somehow broken, but still no result, it only shows the constants).
![изображение](https://user-images.githubusercontent.com/73489604/129907686-8f7ff3b4-a0af-4d5e-9d97-931f33942dfe.png)

**Comment by x87** [comment]
There are three problems with enums.

1. The enums.txt parser correctly rejects enums whose fields are not valid identifiers (starts with a-z_,contains a-z0-9_). Example: `GarageType` contained a field called `60Seconds`. This was fixed by adding extra validation rules in SBL and fixing wrong names. One should redownload the latest enums.txt.
2. The enums.txt parser incorrectly rejects enums whose values are negative numbers (e.g. `Any=-1` in `GangModelOverride`). This will be fixed in the core.dll update https://github.com/sannybuilder/core/pull/10
3. The enums.txt parsers stops on the first error and does not try to load the remaining enum definitions. This is why `ScriptSound` enum from OP does not appear on the list. That enum itself is correct, but preceding errors prevents it from being loaded. This behavior is acceptable, but might be misleading as it does not tell exactly what went wrong.
