### ISSUE TITLE
Can make it possible to create labels with the TAB key?

### ISSUE THREAD

**Issue by wmysterio** [sannybuilder/dev#46]
Is it possible to use the `TAB` key (or define some other) in a certain place, so that then a certain action is performed? For example: I write code like this:

```text
jf @label
```

After that, I press that key, and at the end of the code, a label is inserted if it does not exist:

```text
jf @label
//...

:label // +++
```

It will help save a time for jump tables and more.

**Comment by x87** [comment]
this looks like a very niche use case, so I would not expect this any time soon. However would be cool if Sanny supported plugins that could add this functionality.

**Comment by MatiDragon-YT** [comment]
The possibility of adding addons to the SB, I think it would be great, but leaving a label every time I press `TAB` could be a bit chaotic for those who code with the high level syntax and like to have things more organized with the `tab`.
Although you can create labels with [macros/templates](https://docs.sannybuilder.com/edit-modes/code-templates "Code Templates")... in my case, I create a `:label_00` with letter `k`

----
It occurred to me that maybe I could add an "AUTO-TAB" by hitting `enter` at the end of each `IF`, `THEN`, `ELSE`, `WHILE`, `REPEAT` and `FOR`. Although this can also be done with macros, it would be more convenient this way.
* In the same way, these could be activated and deactivated from the editor options, of course, if things are organized, since there is some space available between them. For example, `Font` has a slightly larger margin than the rest. and / or its content could perhaps be moved to `Colors`, thereby obtaining more space for new options, although the margin of` Looking deeph (lines) `would also have to be corrected to fit everything.
<div align="center"><img src="https://user-images.githubusercontent.com/43966706/94751941-3839fc00-0360-11eb-88fb-66609800162d.png"/></div>

**Comment by MatiDragon-YT** [comment]
The possibility of adding addons to the SB, I think it would be great, but leaving a label every time I press `TAB` could be a bit chaotic for those who code with the high level syntax and like to have things more organized with the `tab`.
Although you can create labels with [macros/templates](https://docs.sannybuilder.com/edit-modes/code-templates "Code Templates")... in my case, I create a `:label_00` with letter `k`

----
It occurred to me that maybe I could add an "AUTO-TAB" by hitting `enter` at the end of each `IF`, `THEN`, `ELSE`, `WHILE`, `REPEAT` and `FOR`. Although this can also be done with macros, it would be more convenient this way.
* In the same way, these could be activated and deactivated from the editor options, of course, if things are organized, since there is some space available between them. For example, `Font` has a slightly larger margin than the rest. and / or its content could perhaps be moved to `Colors`, thereby obtaining more space for new options, although the margin of` Looking deeph (lines) `would also have to be corrected to fit everything.
<div align="center"><img src="https://user-images.githubusercontent.com/43966706/94751941-3839fc00-0360-11eb-88fb-66609800162d.png"/></div>

**Comment by wmysterio** [comment]
@MatiDragon-YT, `TAB` key it is example. The point is not about a specific button. I just want to add the ability to insert non-existing labels from the line.

You `options` interface is nice! But `Font`  it is not `Color`! Maybe need rename `Color` name to `Style`.
