### ISSUE TITLE
Problems at converting cleo to android

### ISSUE THREAD

**Issue by molonov** [sannybuilder/dev#67]
[Screenshot_20200901-142340_ExaGear - Windows Emulator](https://user-images.githubusercontent.com/70562056/91797934-c2f2e280-ec5e-11ea-9733-df097d26d2a1.jpg)
![Screenshot_20200901-142316_ExaGear - Windows Emulator](https://user-images.githubusercontent.com/70562056/91797940-c5553c80-ec5e-11ea-922c-0774467209f4.jpg)

Hello, I am really newbie to use sanny builder, And I wanted to convert AL_Planes and other pc cleos to android.

I changed 00E1 for android like to key_pressed 3 touch_point 1 etc, and changed (CLEO.csa). 
And I fixed all red words which has errors to Compile, I changed all but compiler always say one left to parameters.

 I tried to find more red words, but there isn't.
I tried my best, All scripts looks like normal, And I really want to fix it. can someone advise/help or covert this file for me?

**Comment by OrionSR** [comment]
Oh no! Lots of problem here, starting with:

This isn't a good site for asking for help learning to code. For questions like this I would suggest the [GTA III, VC & SA Coding subforum]( https://gtaforums.com/forum/317-coding/) at GTAForums. If you post a new topic there I'm sure to find it, but I'm not sure how much help I can be with this particular question.

Those red words, however, are an appropriate issue for this site because without modifications to the edit mode and special setup instructions, **Sanny can't compile object IDs for sa_mobile**. I'm assuming the red words always started with a hash tag - something like #OBJECTNAME and the red was a little darker than quoted text. (I'm working to resolve this problem.)

For now, switch to SA mode and see if you can convert the hashed object IDs to object number using Sanny's Ctrl-Alt-H function.  The object numbers should compile properly using the sa_mobile mode. **However, my conversion tool is broken again.** I tried changing the hotkeys but this time it doesn't help. I need to open an issue on this but haven't followed through with all my options yet.

Judging from your screenshot, either you made some serious mistakes trying to decompile this script, like starting with a VC script, or more likely, the author tried to lock this script to make it more difficult to decompile. Two major problems with unlocking a script; 1) You don't have permission to modify it so you'll need to commit to learning how it works well enough to write a completely new script from scratch if you hope to share your work. 2) This script is a poor choice for a newbie to use as an example to convert from one system to another. 

Try starting with a better script - something that decompiles without setting IGNORE_UNKNOWN. And while you're at it, please disable CODE_OFFSETS; they aren't particularly useful for this purpose and just clutter the page.

**Comment by XMDS** [comment]
@OrionSR 
 I think we should create an Android CLEO theme in the gta forum.  To discuss the writing of Android CLEO and some issues.  You have a topic about reading and writing memory in SCM before, and it is great.  There are more and more Android CLEO writers.  But many writers choose to encrypt CLEO, which is actually not good.  Of course, I actually have some research on how to encrypt some methods, if you are interested.  I think you also have some results of Android CLEO, if possible, I hope to share.

@x87  
Before the issue is closed.  In the help file of the SB tool, there is a detailed explanation about CLEO3OP. I think this information can be improved and CLEO4 can be added.  In fact, what I want to say is that I think it is also necessary to write a detailed information about the new OP of CLEO for Android made by Alex.  In fact, many ODDX OPs on Android don't understand the meaning.  I have considered writing this information.

**Comment by x87** [comment]
>Before the issue is closed. In the help file of the SB tool, there is a detailed explanation about CLEO3OP. I think this information can be improved and CLEO4 can be added. In fact, what I want to say is that I think it is also necessary to write a detailed information about the new OP of CLEO for Android made by Alex. In fact, many ODDX OPs on Android don't understand the meaning. I have considered writing this information.

if someone is willing to compile this documentation in [Markdown](https://en.wikipedia.org/wiki/Markdown) form I will be more than happy to add it on cleo.li and docs.sannybuilder.com

**Comment by GoKuDead** [comment]
Good afternoon, night or day for everyone, how are you, friends, I hope you can help me or guide you on the right path, I am currently a Java language coder and android studio, I have gotten into the GTA sa android v1.08 roll, I use sanny builder to create cleos, I have many questions about cleo android, unfortunately there are not much cleo android bases, so I have some doubts, I will start by saying that I only use the IDA pro version with its hex rays decoiler, with the option of pseudocode (F5) teachers I hope they help me with this, I don't know where to learn IDA or at least asmx86 from pc since cleo android and android .so in the functions look a bit like those of pc, it hurts that android does not use struct for classes, teachers where I can learn ARM I have seen that the version of .so is ARMv7-little endian, I would also like to know how to find data by dumping memory from my favorite editor 010 is a hexagecimal editor.

Teachers I have good ideas that I can help with, but teachers this is another level :(

I hope your countries are well from covid19

**Comment by GoKuDead** [comment]
I have also seen a lot of equality in plugin sdk of dk22pac and cleo the .so of android

**Comment by OrionSR** [comment]
Check [this topic](https://gtaforums.com/topic/926144-gta-sa-android-scm-write-memory-address-value/page/2/) on GTAForums.com. The topic was specific to using aDMA strategies to manage Android memory but also includes some basic info on managing Android memory and has a link to a Sheet where I was recording v1.08 memory addresses and their labels.

Further discussion would be more appropriate on [GTAForums](https://gtaforums.com/forum/332-gta-iii-vc-sa/) as this really isn't a Sanny specific issue and anything we learn will be more easily found by other users.

**Comment by GoKuDead** [comment]
> Check [this topic](https://gtaforums.com/topic/926144-gta-sa-android-scm-write-memory-address-value/page/2/) on GTAForums.com. The topic was specific to using aDMA strategies to manage Android memory but also includes some basic info on managing Android memory and has a link to a Sheet where I was recording v1.08 memory addresses and their labels.
> 
> Further discussion would be more appropriate on [GTAForums](https://gtaforums.com/forum/332-gta-iii-vc-sa/) as this really isn't a Sanny specific issue and anything we learn will be more easily found by other users.

currently I need a good information base, the addresses as an image base is usually a bit easy to handle, what is quite difficult are the reversing of arm, teacher can be my friend, I am interested in memory dump using 010, or from ps2 whatever I only need a base, I have plenty of tools :)

**Comment by GoKuDead** [comment]
Also ADMA I know what it is but I don't know how to use it, I have seen that they are used in global and local variables but my knowledge about adma is quite small?
Can you give me a file on adma?

**Comment by OrionSR** [comment]
Don't worry about aDMA unless you need to read or write to memory without cleo.

My IDA skills are quite low. I don't know how to make any sense out of anything I try to disassemble. I have had some success finding data in PC memory and adapting that knowledge to PS2 and Android.

I use PC processes memory as my primary reference as it's a dynamic memory space - I can try things and see what changes. 010 is my preferred editor but my version (6.0.3) doesn't manage process memory very well - the offsets shown in 010 don't match the game memory offsets. 010 upgrade notes don't show any improvements in this area. I usually use HxD if I need to work with PC memory; this tool can probably make a good memory dump for 010 if needed.

Save States from PCSX2 can be used directly as memory dumps from PS2. My current PCs can't run the PCSX2 emulator.

Android memory dumps are a bit more problematic. If your device is rooted then Cheat Engine or something similar might be able to make memory dumps for static reference. I've got a save editing strategy that can provide about 2 MB of memory starting at global variable $0, but that leaves out a lot of valuable data. Another trick lets me copy about 200,000 bytes of memory to the global variable space for analysis; trying to piece together a full dump using this strategy would be quite difficult though.

Again, this discussion would be more appropriate at GTAForums, and will be more likely to be seen by players with more expertise in some of these areas.

**Comment by GoKuDead** [comment]
> Don't worry about aDMA unless you need to read or write to memory without cleo.
> 
> My IDA skills are quite low. I don't know how to make any sense out of anything I try to disassemble. I have had some success finding data in PC memory and adapting that knowledge to PS2 and Android.
> 
> I use PC processes memory as my primary reference as it's a dynamic memory space - I can try things and see what changes. 010 is my preferred editor but my version (6.0.3) doesn't manage process memory very well - the offsets shown in 010 don't match the game memory offsets. 010 upgrade notes don't show any improvements in this area. I usually use HxD if I need to work with PC memory; this tool can probably make a good memory dump for 010 if needed.
> 
> Save States from PCSX2 can be used directly as memory dumps from PS2. My current PCs can't run the PCSX2 emulator.
> 
> Android memory dumps are a bit more problematic. If your device is rooted then Cheat Engine or something similar might be able to make memory dumps for static reference. I've got a save editing strategy that can provide about 2 MB of memory starting at global variable $0, but that leaves out a lot of valuable data. Another trick lets me copy about 200,000 bytes of memory to the global variable space for analysis; trying to piece together a full dump using this strategy would be quite difficult though.
> 
> Again, this discussion would be more appropriate at GTAForums, and will be more likely to be seen by players with more expertise in some of these areas.

I currently use cheat engine and its ceserver_x86 server, since I do not have a device compatible with gta android, I would like to know how to do memory dump in 010, I have the 010 template of yours, which supports multiple gta, I do not edit it or anything, master I have a pc that supports the ps2 emulator, I also use physical ps2 game by usb I use freemcboot, and opl, if you need tests of mods in ps2, do not hesitate to let me know I will be attentive.

**Comment by GoKuDead** [comment]
> Don't worry about aDMA unless you need to read or write to memory without cleo.
> 
> My IDA skills are quite low. I don't know how to make any sense out of anything I try to disassemble. I have had some success finding data in PC memory and adapting that knowledge to PS2 and Android.
> 
> I use PC processes memory as my primary reference as it's a dynamic memory space - I can try things and see what changes. 010 is my preferred editor but my version (6.0.3) doesn't manage process memory very well - the offsets shown in 010 don't match the game memory offsets. 010 upgrade notes don't show any improvements in this area. I usually use HxD if I need to work with PC memory; this tool can probably make a good memory dump for 010 if needed.
> 
> Save States from PCSX2 can be used directly as memory dumps from PS2. My current PCs can't run the PCSX2 emulator.
> 
> Android memory dumps are a bit more problematic. If your device is rooted then Cheat Engine or something similar might be able to make memory dumps for static reference. I've got a save editing strategy that can provide about 2 MB of memory starting at global variable $0, but that leaves out a lot of valuable data. Another trick lets me copy about 200,000 bytes of memory to the global variable space for analysis; trying to piece together a full dump using this strategy would be quite difficult though.
> 
> Again, this discussion would be more appropriate at GTAForums, and will be more likely to be seen by players with more expertise in some of these areas.

and stop saying that you are not an expert, you are a great teacher who is not an expert does not even know a byte.
you are a great crack and programmer, from which I would like to learn.

**Comment by GoKuDead** [comment]
good afternoon I want to read in cleo android as an example a floating value I get only in integer value, through buffer I want to show it with decimal point, like this 3.1416

//ReadBuffer, and WriteBuffer;

{$CLEO .csi}
{$NOSOURCE}

//-ReadBuffer_WriteBuffer-----

03A4: name_thread "Buffer"
 
//variable Read, Write float pi=3.141599
var
   1@: int
   2@: int
end

:Buffer_0
while true
0001: wait 0 ms 
0007: 1@ = 3 //pi 
0DD0: 0@ >= @BufferDec label code  //salto a la etiqueta donde se lee el formato del Buffer
0DD9: write_mem_addr 0@ value 1@ size 4 add_ib 0 protect 0  //escribimos en el Buffer el numero 3.1416
0DD8: 2@ = read_mem_addr 0@ size 4 fix_ib 0  //leemos el valor 3.1416 en Buffer 
03F0: enable_text_draw 0 //activamos el texto
0343: set_text_draw_linewidth 640.0 
033F: set_text_draw_letter_size 2.0 2.0
045A: draw_text_1number 100.0 100.0 GXT 'NUMBER' number 2@  // ALL RACES WON!~n~~w~$~1~
03F0: enable_text_draw 1 
end

:BufferDec
hex
   00 00 00 00
end

**Comment by OrionSR** [comment]
Oh yeah... Unnecessarily large quotes, and refusal to take the conversation to an appropriate location. I remember you. You're the same dweeb that spammed up the topic where I was working on [embedded scripts for PS2](https://gtaforums.com/topic/956184-help-with-codebreakerweather-cheats-ps2/).

I'm still mad about that, and it's no fun trying to help someone that won't listen to or follow instructions. Go away and leave me alone.
